version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: infra/Dockerfile.server
    ports:
      - "8000:8000"
    environment:
      - DEMO_MODE=true
      - DATABASE_URL=sqlite:///./kokonaisturva.db
      - SECRET_KEY=demo-secret-key
      - API_HOST=0.0.0.0
      - API_PORT=8000
    volumes:
      - ./server:/app
      - server_data:/app/data
    restart: unless-stopped

  client:
    build:
      context: .
      dockerfile: infra/Dockerfile.client
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
    restart: unless-stopped

volumes:
  server_data:
