-- Civitas Comprehensive Seed Data
-- 100 realistic Finnish civilians for demo and testing

-- Insert users from Helsinki region
INSERT INTO users (national_id_hash, full_name, dob, address, lat, lon) VALUES
('hash_hel_001', 'Aino Virtanen', '1987-03-15', 'Mannerheimintie 1, 00100 Helsinki', 60.1699, 24.9384),
('hash_hel_002', 'Eero Nieminen', '1991-07-22', 'Unioninkatu 25, 00170 Helsinki', 60.1719, 24.9414),
('hash_hel_003', 'Sofia Korhonen', '1985-11-08', 'Kaisaniemenkatu 3, 00100 Helsinki', 60.1708, 24.9439),
('hash_hel_004', 'Mikko Mäkelä', '1992-05-12', 'Fredrikinkatu 22, 00120 Helsinki', 60.1636, 24.9271),
('hash_hel_005', 'Liisa Salminen', '1983-09-30', 'Bulevardi 12, 00120 Helsinki', 60.1649, 24.9271),
('hash_hel_006', 'Jukka Koskinen', '1988-12-03', 'Esplanadi 15, 00130 Helsinki', 60.1676, 24.9439),
('hash_hel_007', 'Anna Rantanen', '1975-06-18', 'Aleksanterinkatu 50, 00100 Helsinki', 60.1699, 24.9414),
('hash_hel_008', 'Pekka Järvinen', '1991-04-25', 'Pohjoisesplanadi 35, 00130 Helsinki', 60.1676, 24.9439),
('hash_hel_009', 'Eeva Hämäläinen', '1986-08-14', 'Kluuvikatu 8, 00100 Helsinki', 60.1697, 24.9455),
('hash_hel_010', 'Matti Laine', '1989-01-30', 'Kampinkatu 2, 00100 Helsinki', 60.1695, 24.9318),

-- Insert users from Tampere region
('hash_tam_011', 'Kaisa Heinonen', '1984-06-12', 'Hämeenkatu 20, 33100 Tampere', 61.4991, 23.7871),
('hash_tam_012', 'Jari Toivonen', '1990-09-05', 'Keskustori 1, 33100 Tampere', 61.4982, 23.7616),
('hash_tam_013', 'Marja Lehtinen', '1987-12-18', 'Satakunnankatu 15, 33100 Tampere', 61.4963, 23.7602),
('hash_tam_014', 'Antti Saarinen', '1985-04-03', 'Kalevan puistotie 4, 33500 Tampere', 61.5025, 23.7756),
('hash_tam_015', 'Sanna Väisänen', '1993-07-25', 'Pirkankatu 8, 33100 Tampere', 61.4975, 23.7623),

-- Insert users from Turku region
('hash_tur_016', 'Marko Hakkarainen', '1986-02-14', 'Aurakatu 12, 20100 Turku', 60.4518, 22.2666),
('hash_tur_017', 'Riikka Mattila', '1991-10-08', 'Kauppiaskatu 25, 20100 Turku', 60.4503, 22.2754),
('hash_tur_018', 'Juha Kinnunen', '1988-05-22', 'Humalistonkatu 7, 20100 Turku', 60.4545, 22.2612),
('hash_tur_019', 'Pirjo Rissanen', '1984-11-16', 'Linnankatu 18, 20100 Turku', 60.4521, 22.2698),
('hash_tur_020', 'Timo Aaltonen', '1990-03-29', 'Eerikinkatu 14, 20100 Turku', 60.4498, 22.2675),

-- Insert users from Oulu region
('hash_oul_021', 'Petri Karjalainen', '1987-08-11', 'Kauppurienkatu 10, 90100 Oulu', 65.0121, 25.4651),
('hash_oul_022', 'Helena Koskela', '1992-01-27', 'Kirkkokatu 22, 90100 Oulu', 65.0135, 25.4687),
('hash_oul_023', 'Seppo Laaksonen', '1985-06-04', 'Hallituskatu 6, 90100 Oulu', 65.0118, 25.4623),
('hash_oul_024', 'Marika Turunen', '1989-09-17', 'Pakkahuoneenkatu 3, 90100 Oulu', 65.0128, 25.4645),
('hash_oul_025', 'Jorma Partanen', '1983-12-02', 'Saaristonkatu 15, 90100 Oulu', 65.0132, 25.4667),

-- Insert users from Kuopio region
('hash_kup_026', 'Tuula Moilanen', '1986-04-19', 'Kauppakatu 12, 70100 Kuopio', 62.8924, 27.6770),
('hash_kup_027', 'Kalevi Rantala', '1991-07-13', 'Kauppakatu 25, 70100 Kuopio', 62.8921, 27.6765),
('hash_kup_028', 'Päivi Heikkinen', '1988-10-26', 'Kauppakatu 8, 70100 Kuopio', 62.8927, 27.6775),
('hash_kup_029', 'Heikki Niemi', '1984-02-08', 'Kauppakatu 18, 70100 Kuopio', 62.8923, 27.6768),
('hash_kup_030', 'Sirpa Kärkkäinen', '1990-05-31', 'Kauppakatu 5, 70100 Kuopio', 62.8925, 27.6772),

-- Insert users from Jyväskylä region
('hash_jyv_031', 'Risto Hiltunen', '1987-11-24', 'Kauppakatu 9, 40100 Jyväskylä', 62.2415, 25.7209),
('hash_jyv_032', 'Auli Kivinen', '1993-03-07', 'Kauppakatu 21, 40100 Jyväskylä', 62.2412, 25.7205),
('hash_jyv_033', 'Mauri Lindholm', '1985-08-20', 'Kauppakatu 14, 40100 Jyväskylä', 62.2418, 25.7213),
('hash_jyv_034', 'Leena Peltola', '1989-01-15', 'Kauppakatu 27, 40100 Jyväskylä', 62.2410, 25.7203),
('hash_jyv_035', 'Esko Virtanen', '1986-06-28', 'Kauppakatu 16, 40100 Jyväskylä', 62.2416, 25.7211),

-- Insert users from Rovaniemi region
('hash_rov_036', 'Lauri Kangas', '1988-09-12', 'Korkalonkatu 11, 96200 Rovaniemi', 66.5039, 25.7294),
('hash_rov_037', 'Tarja Miettinen', '1992-12-05', 'Korkalonkatu 24, 96200 Rovaniemi', 66.5036, 25.7291),
('hash_rov_038', 'Ville Peltola', '1984-05-18', 'Korkalonkatu 7, 96200 Rovaniemi', 66.5042, 25.7297),
('hash_rov_039', 'Riitta Savolainen', '1990-02-21', 'Korkalonkatu 19, 96200 Rovaniemi', 66.5038, 25.7295),
('hash_rov_040', 'Pertti Kallio', '1987-07-14', 'Korkalonkatu 13, 96200 Rovaniemi', 66.5040, 25.7296),

-- Insert users from Lahti region
('hash_lah_041', 'Hanna Nieminen', '1985-10-03', 'Vapaudenkatu 15, 15100 Lahti', 60.9827, 25.6612),
('hash_lah_042', 'Tero Mäkinen', '1991-04-16', 'Vapaudenkatu 28, 15100 Lahti', 60.9824, 25.6609),
('hash_lah_043', 'Outi Koskinen', '1988-11-29', 'Vapaudenkatu 12, 15100 Lahti', 60.9830, 25.6615),
('hash_lah_044', 'Janne Salminen', '1986-06-12', 'Vapaudenkatu 21, 15100 Lahti', 60.9826, 25.6611),
('hash_lah_045', 'Sari Rantanen', '1993-01-25', 'Vapaudenkatu 9, 15100 Lahti', 60.9832, 25.6617),

-- Insert users from Vaasa region
('hash_vas_046', 'Mikael Johansson', '1987-08-08', 'Vaasanpuistikko 14, 65100 Vaasa', 63.0959, 21.6158),
('hash_vas_047', 'Camilla Andersson', '1992-03-21', 'Vaasanpuistikko 27, 65100 Vaasa', 63.0956, 21.6155),
('hash_vas_048', 'Lars Eriksson', '1984-10-04', 'Vaasanpuistikko 11, 65100 Vaasa', 63.0962, 21.6161),
('hash_vas_049', 'Anna Lindqvist', '1990-05-17', 'Vaasanpuistikko 23, 65100 Vaasa', 63.0957, 21.6156),
('hash_vas_050', 'Erik Nyström', '1988-12-30', 'Vaasanpuistikko 18, 65100 Vaasa', 63.0960, 21.6159),

-- Insert remaining users from various regions
('hash_por_051', 'Kristiina Honkanen', '1986-07-23', 'Vapaudenkatu 12, 28100 Pori', 61.4852, 21.7974),
('hash_por_052', 'Jarmo Seppälä', '1991-02-16', 'Vapaudenkatu 25, 28100 Pori', 61.4850, 21.7972),
('hash_por_053', 'Tiina Aho', '1988-09-09', 'Vapaudenkatu 8, 28100 Pori', 61.4854, 21.7976),
('hash_por_054', 'Mika Laine', '1984-04-22', 'Vapaudenkatu 19, 28100 Pori', 61.4851, 21.7973),
('hash_por_055', 'Sanna Kinnunen', '1990-11-05', 'Vapaudenkatu 6, 28100 Pori', 61.4855, 21.7977),

('hash_joen_056', 'Pekka Hämäläinen', '1987-06-18', 'Koskikatu 14, 80100 Joensuu', 62.6010, 29.7636),
('hash_joen_057', 'Marja Lehtonen', '1993-01-11', 'Koskikatu 27, 80100 Joensuu', 62.6007, 29.7633),
('hash_joen_058', 'Antti Kärkkäinen', '1985-08-24', 'Koskikatu 11, 80100 Joensuu', 62.6013, 29.7639),
('hash_joen_059', 'Riikka Virtanen', '1989-03-07', 'Koskikatu 23, 80100 Joensuu', 62.6008, 29.7634),
('hash_joen_060', 'Timo Saarinen', '1986-10-20', 'Koskikatu 16, 80100 Joensuu', 62.6011, 29.7637),

('hash_sein_061', 'Helena Nieminen', '1988-05-13', 'Kauppakatu 13, 60100 Seinäjoki', 62.7908, 22.8404),
('hash_sein_062', 'Jukka Korhonen', '1992-12-26', 'Kauppakatu 26, 60100 Seinäjoki', 62.7905, 22.8401),
('hash_sein_063', 'Anna Mäkelä', '1984-09-09', 'Kauppakatu 9, 60100 Seinäjoki', 62.7911, 22.8407),
('hash_sein_064', 'Mikko Salminen', '1990-04-22', 'Kauppakatu 21, 60100 Seinäjoki', 62.7906, 22.8402),
('hash_sein_065', 'Liisa Rantanen', '1987-11-15', 'Kauppakatu 17, 60100 Seinäjoki', 62.7909, 22.8405),

('hash_kot_066', 'Eero Hiltunen', '1985-02-28', 'Kauppakatu 12, 48100 Kotka', 60.4669, 26.9460),
('hash_kot_067', 'Kaisa Lindholm', '1991-09-11', 'Kauppakatu 25, 48100 Kotka', 60.4666, 26.9457),
('hash_kot_068', 'Jari Peltola', '1988-06-24', 'Kauppakatu 8, 48100 Kotka', 60.4672, 26.9463),
('hash_kot_069', 'Marja Virtanen', '1984-01-07', 'Kauppakatu 20, 48100 Kotka', 60.4667, 26.9458),
('hash_kot_070', 'Antti Koskinen', '1990-08-20', 'Kauppakatu 15, 48100 Kotka', 60.4670, 26.9461),

('hash_hel_071', 'Sofia Hämäläinen', '1986-03-03', 'Kluuvikatu 8, 00100 Helsinki', 60.1697, 24.9455),
('hash_hel_072', 'Matti Laine', '1989-01-30', 'Kampinkatu 2, 00100 Helsinki', 60.1695, 24.9318),
('hash_hel_073', 'Eeva Virtanen', '1987-08-14', 'Unioninkatu 15, 00170 Helsinki', 60.1715, 24.9410),
('hash_hel_074', 'Pekka Nieminen', '1991-05-27', 'Kaisaniemenkatu 5, 00100 Helsinki', 60.1705, 24.9435),
('hash_hel_075', 'Anna Korhonen', '1988-12-10', 'Fredrikinkatu 18, 00120 Helsinki', 60.1633, 24.9268),

('hash_hel_076', 'Jukka Mäkelä', '1985-09-23', 'Bulevardi 8, 00120 Helsinki', 60.1646, 24.9268),
('hash_hel_077', 'Liisa Salminen', '1992-04-06', 'Esplanadi 12, 00130 Helsinki', 60.1673, 24.9436),
('hash_hel_078', 'Mikko Rantanen', '1986-11-19', 'Aleksanterinkatu 45, 00100 Helsinki', 60.1696, 24.9411),
('hash_hel_079', 'Sanna Järvinen', '1990-06-02', 'Pohjoisesplanadi 30, 00130 Helsinki', 60.1673, 24.9436),
('hash_hel_080', 'Eero Koskinen', '1987-01-15', 'Mannerheimintie 15, 00100 Helsinki', 60.1699, 24.9384),

('hash_hel_081', 'Aino Hiltunen', '1984-10-28', 'Unioninkatu 30, 00170 Helsinki', 60.1722, 24.9417),
('hash_hel_082', 'Timo Lindholm', '1991-07-11', 'Kaisaniemenkatu 8, 00100 Helsinki', 60.1711, 24.9442),
('hash_hel_083', 'Marja Peltola', '1988-02-24', 'Fredrikinkatu 25, 00120 Helsinki', 60.1639, 24.9274),
('hash_hel_084', 'Antti Virtanen', '1985-09-07', 'Bulevardi 15, 00120 Helsinki', 60.1652, 24.9274),
('hash_hel_085', 'Riikka Koskinen', '1992-04-20', 'Esplanadi 18, 00130 Helsinki', 60.1679, 24.9442),

('hash_hel_086', 'Jukka Nieminen', '1986-11-03', 'Aleksanterinkatu 55, 00100 Helsinki', 60.1702, 24.9417),
('hash_hel_087', 'Anna Järvinen', '1990-06-16', 'Pohjoisesplanadi 40, 00130 Helsinki', 60.1679, 24.9442),
('hash_hel_088', 'Mikko Koskinen', '1987-01-29', 'Mannerheimintie 25, 00100 Helsinki', 60.1705, 24.9384),
('hash_hel_089', 'Sanna Hiltunen', '1984-10-12', 'Unioninkatu 35, 00170 Helsinki', 60.1728, 24.9423),
('hash_hel_090', 'Eero Lindholm', '1991-07-25', 'Kaisaniemenkatu 12, 00100 Helsinki', 60.1717, 24.9448),

('hash_hel_091', 'Aino Peltola', '1988-02-08', 'Fredrikinkatu 30, 00120 Helsinki', 60.1645, 24.9280),
('hash_hel_092', 'Timo Virtanen', '1985-09-21', 'Bulevardi 20, 00120 Helsinki', 60.1658, 24.9280),
('hash_hel_093', 'Marja Koskinen', '1992-04-04', 'Esplanadi 22, 00130 Helsinki', 60.1685, 24.9448),
('hash_hel_094', 'Antti Nieminen', '1986-11-17', 'Aleksanterinkatu 60, 00100 Helsinki', 60.1708, 24.9423),
('hash_hel_095', 'Riikka Järvinen', '1990-06-30', 'Pohjoisesplanadi 45, 00130 Helsinki', 60.1685, 24.9448),

('hash_hel_096', 'Jukka Koskinen', '1987-01-13', 'Mannerheimintie 30, 00100 Helsinki', 60.1711, 24.9390),
('hash_hel_097', 'Anna Hiltunen', '1984-10-26', 'Unioninkatu 40, 00170 Helsinki', 60.1734, 24.9429),
('hash_hel_098', 'Mikko Lindholm', '1991-07-09', 'Kaisaniemenkatu 15, 00100 Helsinki', 60.1723, 24.9454),
('hash_hel_099', 'Sanna Peltola', '1988-02-22', 'Fredrikinkatu 35, 00120 Helsinki', 60.1651, 24.9286),
('hash_hel_100', 'Eero Virtanen', '1985-09-05', 'Bulevardi 25, 00120 Helsinki', 60.1664, 24.9286);

-- Insert comprehensive profiles with diverse skills and backgrounds
INSERT INTO profiles (user_id, education_level, skills, free_text, availability, capability_score, tags_json, status) VALUES
(1, 'masters', '["cybersecurity", "network security", "penetration testing", "medical"]', 'Experienced cybersecurity specialist and paramedic with 10 years in emergency services. Certified in advanced life support and network security. Former military communications officer with expertise in secure communications and digital forensics.', 'allocated', 92.0, '["cybersecurity", "medical", "defense", "technical"]', 'allocated'),
(2, 'bachelors', '["translation", "communication", "english", "russian", "swedish"]', 'Professional translator fluent in multiple languages with crisis communication experience. Worked with international aid organizations during emergencies. Certified in emergency interpreting and cross-cultural communication.', '24h', 78.0, '["communication", "international"]', 'available'),
(3, 'vocational', '["construction", "heavy machinery", "safety", "logistics", "welding"]', 'Construction supervisor with access to heavy machinery and vehicles. Safety certified with 15 years experience in infrastructure projects. Skilled in emergency repairs and temporary shelter construction.', 'immediate', 85.0, '["technical", "logistics", "construction"]', 'available'),
(4, 'masters', '["psychology", "counseling", "mental health", "crisis intervention"]', 'Clinical psychologist specializing in trauma and crisis intervention. Available for mental health support with experience in disaster psychology and community resilience building.', '48h', 82.0, '["medical", "crisis_intervention"]', 'available'),
(5, 'bachelors', '["IT", "network administration", "communication systems", "radio", "cybersecurity"]', 'IT specialist with expertise in communication systems and radio networks. Can set up emergency communications infrastructure and maintain network security during crisis situations.', 'allocated', 88.0, '["technical", "communication", "cybersecurity"]', 'allocated'),
(6, 'associate', '["nursing", "first aid", "medical equipment", "hospital", "emergency medicine"]', 'Registered nurse with experience in emergency medicine. Can provide medical support and coordinate with hospitals. Certified in trauma care and disaster medicine protocols.', '24h', 86.0, '["medical", "emergency_medicine"]', 'available'),
(7, 'high_school', '["driving", "transport", "logistics", "fuel", "heavy vehicles"]', 'Professional driver with commercial license for heavy vehicles. Access to multiple vehicles and fuel resources. Experienced in emergency logistics and supply chain management.', 'immediate', 72.0, '["logistics", "transport"]', 'available'),
(8, 'masters', '["management", "coordination", "public relations", "media", "crisis management"]', 'Former crisis manager with experience in coordinating emergency responses and public communication. Skilled in resource allocation and inter-agency coordination during large-scale emergencies.', '24h', 90.0, '["leadership", "communication", "crisis_management"]', 'available'),
(9, 'bachelors', '["drones", "UAV", "aerial surveillance", "photography", "mapping"]', 'Commercial drone pilot with advanced UAV certifications. Specializes in aerial surveillance, mapping, and search operations. Has thermal imaging capabilities and can operate in various weather conditions.', 'immediate', 84.0, '["drones", "surveillance", "technical"]', 'available'),
(10, 'vocational', '["electrical", "power systems", "generators", "solar", "emergency power"]', 'Licensed electrician with expertise in emergency power systems and generators. Can restore power infrastructure and set up temporary electrical systems for emergency shelters.', 'immediate', 87.0, '["electrical", "power_systems", "technical"]', 'available'),
(11, 'masters', '["automation", "PLC programming", "industrial systems", "robotics"]', 'Senior automation engineer with 12 years experience in industrial robotics and PLC programming. Expert in SCADA systems and can provide technical support for critical infrastructure.', '24h', 91.0, '["automation", "robotics", "technical"]', 'available'),
(12, 'bachelors', '["mechanical engineering", "heavy machinery", "repairs", "hydraulics"]', 'Mechanical engineer specializing in heavy machinery and hydraulic systems. Can perform emergency repairs on vehicles and equipment. Experience with industrial maintenance and troubleshooting.', 'immediate', 83.0, '["mechanical", "technical", "repairs"]', 'available'),
(13, 'associate', '["welding", "metalwork", "fabrication", "repairs", "construction"]', 'Certified welder with expertise in structural welding and metal fabrication. Can perform emergency repairs on infrastructure and vehicles. Skilled in various welding techniques and materials.', 'immediate', 79.0, '["welding", "metalwork", "technical"]', 'available'),
(14, 'bachelors', '["logistics", "supply chain", "warehouse management", "inventory"]', 'Supply chain specialist with experience in emergency logistics and warehouse management. Can coordinate resource distribution and maintain inventory systems during crisis situations.', '24h', 76.0, '["logistics", "supply_chain"]', 'available'),
(15, 'masters', '["medicine", "emergency medicine", "surgery", "trauma care"]', 'Emergency medicine physician with extensive trauma care experience. Can provide advanced medical support and coordinate medical teams during emergencies. Board certified in emergency medicine.', 'allocated', 95.0, '["medical", "emergency_medicine", "trauma_care"]', 'allocated'),
(16, 'bachelors', '["radio communications", "HAM radio", "emergency communications", "networking"]', 'HAM radio operator and emergency communications specialist. Can establish communication networks when infrastructure fails. Licensed for emergency communications and disaster relief operations.', 'immediate', 81.0, '["communication", "radio", "emergency_comms"]', 'available'),
(17, 'vocational', '["carpentry", "construction", "building", "repairs", "shelter"]', 'Master carpenter with 20 years experience in construction and building repairs. Can construct emergency shelters and perform structural repairs. Skilled in traditional and modern building techniques.', 'immediate', 77.0, '["construction", "carpentry", "building"]', 'available'),
(18, 'bachelors', '["water treatment", "environmental engineering", "sanitation", "public health"]', 'Environmental engineer specializing in water treatment and sanitation systems. Can restore water infrastructure and ensure safe drinking water during emergencies. Expert in public health engineering.', '48h', 80.0, '["environmental", "water_treatment", "public_health"]', 'available'),
(19, 'masters', '["data analysis", "information systems", "GIS", "mapping", "coordination"]', 'Information systems specialist with expertise in data analysis and GIS mapping. Can support decision-making with data visualization and coordinate information flow during emergency operations.', '24h', 82.0, '["data_analysis", "GIS", "information_systems"]', 'available'),
(20, 'bachelors', '["firefighting", "rescue operations", "hazmat", "emergency response"]', 'Professional firefighter with specialized training in rescue operations and hazmat response. Can provide emergency rescue services and coordinate fire safety during crisis situations.', 'immediate', 89.0, '["firefighting", "rescue", "emergency_response"]', 'available');
-- Civitas Comprehensive Seed Data - Part 2
-- Profiles 21-100, Resources, Requests, and Allocations

-- Continue profiles (21-50)
(21, 'bachelors', '["marine engineering", "ship repair", "emergency response", "navigation"]', 'Marine engineer with expertise in ship repair and emergency response at sea. Can coordinate maritime rescue operations and provide technical support for marine infrastructure.', '24h', 83.0, '["marine", "emergency_response", "technical"]', 'available'),
(22, 'masters', '["forestry", "environmental science", "wildfire management", "conservation"]', 'Forestry specialist with extensive experience in wildfire management and environmental conservation. Can coordinate forest fire response and environmental protection efforts.', 'immediate', 79.0, '["forestry", "wildfire_management", "environmental"]', 'available'),
(23, 'vocational', '["heavy equipment", "excavation", "earthmoving", "construction"]', 'Heavy equipment operator with 18 years experience in excavation and earthmoving. Can provide equipment support for emergency construction and debris removal operations.', 'immediate', 74.0, '["heavy_equipment", "construction", "excavation"]', 'available'),
(24, 'bachelors', '["telecommunications", "satellite communications", "emergency networks", "IT"]', 'Telecommunications engineer specializing in satellite communications and emergency network setup. Can establish communication infrastructure when terrestrial systems fail.', '24h', 86.0, '["telecommunications", "satellite", "emergency_networks"]', 'available'),
(25, 'associate', '["aviation", "aircraft maintenance", "flight operations", "emergency transport"]', 'Aviation technician with commercial pilot license and aircraft maintenance certification. Can provide emergency air transport and coordinate aviation resources.', 'immediate', 88.0, '["aviation", "emergency_transport", "flight_operations"]', 'available'),
(26, 'masters', '["public health", "epidemiology", "disease control", "medical coordination"]', 'Public health specialist with expertise in epidemiology and disease control. Can coordinate medical response during health emergencies and manage disease surveillance.', '48h', 87.0, '["public_health", "epidemiology", "disease_control"]', 'available'),
(27, 'bachelors', '["geology", "earthquake response", "natural disasters", "risk assessment"]', 'Geologist specializing in earthquake response and natural disaster risk assessment. Can provide technical support for geological hazard evaluation and emergency planning.', '24h', 80.0, '["geology", "earthquake_response", "natural_disasters"]', 'available'),
(28, 'vocational', '["plumbing", "water systems", "sanitation", "emergency repairs"]', 'Master plumber with expertise in water systems and emergency repairs. Can restore water infrastructure and maintain sanitation systems during crisis situations.', 'immediate', 76.0, '["plumbing", "water_systems", "sanitation"]', 'available'),
(29, 'bachelors', '["chemistry", "hazmat", "chemical safety", "decontamination"]', 'Chemical safety specialist with HAZMAT certification and decontamination expertise. Can handle chemical emergencies and coordinate hazardous material response.', 'immediate', 85.0, '["chemistry", "hazmat", "chemical_safety"]', 'available'),
(30, 'masters', '["social work", "community support", "vulnerable populations", "crisis counseling"]', 'Social worker specializing in community support and crisis counseling. Can coordinate support services for vulnerable populations during emergencies.', '24h', 78.0, '["social_work", "community_support", "crisis_counseling"]', 'available'),
(31, 'bachelors', '["civil engineering", "infrastructure", "bridge repair", "structural assessment"]', 'Civil engineer with expertise in infrastructure assessment and bridge repair. Can evaluate structural damage and coordinate infrastructure restoration efforts.', '24h', 84.0, '["civil_engineering", "infrastructure", "structural_assessment"]', 'available'),
(32, 'associate', '["HVAC", "climate control", "ventilation systems", "emergency cooling"]', 'HVAC technician specializing in emergency climate control and ventilation systems. Can restore heating and cooling systems in emergency shelters and facilities.', 'immediate', 73.0, '["HVAC", "climate_control", "ventilation"]', 'available'),
(33, 'bachelors', '["food safety", "nutrition", "emergency feeding", "logistics"]', 'Food safety specialist with experience in emergency feeding operations and nutrition planning. Can coordinate food distribution and ensure food safety during emergencies.', '24h', 77.0, '["food_safety", "emergency_feeding", "nutrition"]', 'available'),
(34, 'masters', '["urban planning", "evacuation planning", "emergency shelter", "spatial analysis"]', 'Urban planner with expertise in evacuation planning and emergency shelter coordination. Can support emergency planning and spatial analysis for crisis response.', '48h', 81.0, '["urban_planning", "evacuation_planning", "emergency_shelter"]', 'available'),
(35, 'vocational', '["refrigeration", "cooling systems", "emergency cooling", "equipment repair"]', 'Refrigeration technician with expertise in emergency cooling systems and equipment repair. Can maintain temperature control systems in emergency situations.', 'immediate', 75.0, '["refrigeration", "cooling_systems", "equipment_repair"]', 'available'),
(36, 'bachelors', '["wildlife management", "animal rescue", "veterinary support", "conservation"]', 'Wildlife management specialist with veterinary support experience. Can coordinate animal rescue operations and provide wildlife conservation support during emergencies.', '24h', 79.0, '["wildlife_management", "animal_rescue", "veterinary_support"]', 'available'),
(37, 'masters', '["energy systems", "power grid", "renewable energy", "emergency power"]', 'Energy systems engineer specializing in power grid restoration and renewable energy systems. Can restore power infrastructure and coordinate emergency energy solutions.', '24h', 86.0, '["energy_systems", "power_grid", "renewable_energy"]', 'available'),
(38, 'bachelors', '["security", "crowd control", "emergency security", "risk management"]', 'Security specialist with experience in crowd control and emergency security operations. Can provide security coordination and risk management during crisis situations.', 'immediate', 82.0, '["security", "crowd_control", "risk_management"]', 'available'),
(39, 'associate', '["landscaping", "tree removal", "debris clearing", "emergency cleanup"]', 'Landscaping specialist with expertise in emergency cleanup and debris removal. Can coordinate environmental cleanup operations and tree removal services.', 'immediate', 71.0, '["landscaping", "debris_clearing", "emergency_cleanup"]', 'available'),
(40, 'bachelors', '["meteorology", "weather forecasting", "storm tracking", "emergency weather"]', 'Meteorologist with expertise in emergency weather forecasting and storm tracking. Can provide weather support for emergency operations and severe weather response.', '24h', 83.0, '["meteorology", "weather_forecasting", "storm_tracking"]', 'available'),
(41, 'masters', '["disaster recovery", "business continuity", "emergency planning", "risk assessment"]', 'Disaster recovery specialist with expertise in business continuity and emergency planning. Can coordinate recovery operations and support organizational resilience.', '48h', 85.0, '["disaster_recovery", "business_continuity", "emergency_planning"]', 'available'),
(42, 'bachelors', '["transportation", "traffic management", "emergency routing", "logistics"]', 'Transportation engineer with expertise in emergency traffic management and routing. Can coordinate transportation systems during emergency evacuations and response.', '24h', 80.0, '["transportation", "traffic_management", "emergency_routing"]', 'available'),
(43, 'vocational', '["crane operation", "heavy lifting", "equipment operation", "construction"]', 'Certified crane operator with expertise in heavy lifting and equipment operation. Can provide heavy equipment support for emergency construction and rescue operations.', 'immediate', 76.0, '["crane_operation", "heavy_lifting", "equipment_operation"]', 'available'),
(44, 'bachelors', '["information security", "cyber defense", "digital forensics", "network protection"]', 'Information security specialist with expertise in cyber defense and digital forensics. Can protect critical systems and investigate cyber incidents during emergencies.', '24h', 89.0, '["information_security", "cyber_defense", "digital_forensics"]', 'available'),
(45, 'associate', '["emergency dispatch", "communication coordination", "radio operations", "call center"]', 'Emergency dispatch specialist with expertise in communication coordination and radio operations. Can manage emergency communications and coordinate response teams.', 'immediate', 78.0, '["emergency_dispatch", "communication_coordination", "radio_operations"]', 'available'),
(46, 'bachelors', '["international relations", "diplomacy", "cross-border coordination", "multilingual"]', 'International relations specialist with diplomatic experience and multilingual capabilities. Can coordinate international assistance and cross-border emergency response.', '48h', 84.0, '["international_relations", "diplomacy", "cross_border_coordination"]', 'available'),
(47, 'masters', '["economics", "resource allocation", "emergency funding", "financial coordination"]', 'Economic analyst with expertise in resource allocation and emergency funding coordination. Can support financial planning and resource optimization during crisis response.', '24h', 82.0, '["economics", "resource_allocation", "emergency_funding"]', 'available'),
(48, 'bachelors', '["law enforcement", "investigation", "evidence collection", "emergency policing"]', 'Law enforcement officer with investigation expertise and emergency policing experience. Can provide security coordination and evidence collection during crisis situations.', 'immediate', 87.0, '["law_enforcement", "investigation", "evidence_collection"]', 'available'),
(49, 'vocational', '["masonry", "stone work", "building repair", "structural restoration"]', 'Master mason with expertise in stone work and building repair. Can perform structural restoration and emergency building repairs using traditional and modern techniques.', 'immediate', 74.0, '["masonry", "stone_work", "building_repair"]', 'available'),
(50, 'bachelors', '["agriculture", "food production", "emergency farming", "rural coordination"]', 'Agricultural specialist with expertise in emergency food production and rural coordination. Can support agricultural operations and coordinate rural emergency response.', '24h', 76.0, '["agriculture", "food_production", "rural_coordination"]', 'available');

-- Continue with profiles 51-100 (simplified for space)
(51, 'bachelors', '["education", "training", "public awareness", "community outreach"]', 'Education specialist with experience in public awareness campaigns and community outreach. Can coordinate public education and training programs during emergencies.', '48h', 73.0, '["education", "public_awareness", "community_outreach"]', 'available'),
(52, 'masters', '["research", "data analysis", "emergency research", "policy development"]', 'Research analyst with expertise in emergency research and policy development. Can support evidence-based decision making and policy coordination during crisis response.', '24h', 79.0, '["research", "data_analysis", "policy_development"]', 'available'),
(53, 'bachelors', '["journalism", "media relations", "public communication", "crisis communication"]', 'Journalist with expertise in crisis communication and media relations. Can coordinate public communication and media management during emergency situations.', '24h', 77.0, '["journalism", "media_relations", "crisis_communication"]', 'available'),
(54, 'vocational', '["painting", "surface preparation", "emergency repairs", "protective coatings"]', 'Professional painter with expertise in surface preparation and protective coatings. Can provide emergency repair services and protective coating applications.', 'immediate', 68.0, '["painting", "surface_preparation", "emergency_repairs"]', 'available'),
(55, 'bachelors', '["library science", "information management", "documentation", "record keeping"]', 'Information specialist with expertise in documentation and record keeping. Can support information management and documentation during emergency operations.', '48h', 72.0, '["library_science", "information_management", "documentation"]', 'available'),
(56, 'masters', '["archaeology", "cultural preservation", "heritage protection", "site assessment"]', 'Archaeologist with expertise in cultural preservation and heritage protection. Can assess and protect cultural sites during emergency situations.', '48h', 75.0, '["archaeology", "cultural_preservation", "heritage_protection"]', 'available'),
(57, 'bachelors', '["music therapy", "mental health", "community healing", "stress relief"]', 'Music therapist with expertise in mental health support and community healing. Can provide therapeutic services and stress relief programs during crisis situations.', '24h', 70.0, '["music_therapy", "mental_health", "community_healing"]', 'available'),
(58, 'associate', '["beauty services", "hygiene support", "personal care", "community wellness"]', 'Beauty specialist with expertise in hygiene support and personal care. Can provide hygiene services and personal care support in emergency shelters.', '24h', 65.0, '["beauty_services", "hygiene_support", "personal_care"]', 'available'),
(59, 'bachelors', '["fitness", "physical therapy", "rehabilitation", "health promotion"]', 'Physical therapist with expertise in rehabilitation and health promotion. Can provide physical therapy services and health promotion programs during emergency response.', '24h', 78.0, '["fitness", "physical_therapy", "rehabilitation"]', 'available'),
(60, 'masters', '["philosophy", "ethics", "decision support", "moral guidance"]', 'Ethics specialist with expertise in decision support and moral guidance. Can provide ethical guidance and decision support during complex emergency situations.', '48h', 76.0, '["philosophy", "ethics", "decision_support"]', 'available'),
(61, 'bachelors', '["theology", "spiritual support", "community healing", "crisis counseling"]', 'Theologian with expertise in spiritual support and crisis counseling. Can provide spiritual guidance and community healing services during emergency situations.', '24h', 74.0, '["theology", "spiritual_support", "crisis_counseling"]', 'available'),
(62, 'vocational', '["housekeeping", "sanitation", "facility maintenance", "cleanup operations"]', 'Facility maintenance specialist with expertise in sanitation and cleanup operations. Can maintain emergency facilities and coordinate cleanup operations.', 'immediate', 69.0, '["housekeeping", "sanitation", "facility_maintenance"]', 'available'),
(63, 'bachelors', '["recreation", "community activities", "stress relief", "mental health support"]', 'Recreation specialist with expertise in community activities and stress relief programs. Can organize recreational activities and mental health support programs.', '24h', 71.0, '["recreation", "community_activities", "stress_relief"]', 'available'),
(64, 'masters', '["anthropology", "cultural awareness", "community relations", "cross-cultural communication"]', 'Anthropologist with expertise in cultural awareness and community relations. Can support cross-cultural communication and community relations during emergency response.', '48h', 78.0, '["anthropology", "cultural_awareness", "community_relations"]', 'available'),
(65, 'bachelors', '["history", "documentation", "record keeping", "heritage preservation"]', 'Historian with expertise in documentation and heritage preservation. Can support historical documentation and heritage preservation during emergency situations.', '24h', 73.0, '["history", "documentation", "heritage_preservation"]', 'available'),
(66, 'associate', '["retail", "inventory management", "supply coordination", "distribution"]', 'Retail specialist with expertise in inventory management and supply coordination. Can support supply chain operations and distribution during emergency response.', '24h', 72.0, '["retail", "inventory_management", "supply_coordination"]', 'available'),
(67, 'bachelors', '["hospitality", "facility management", "accommodation coordination", "service management"]', 'Hospitality manager with expertise in facility management and accommodation coordination. Can manage emergency accommodations and service coordination.', '24h', 75.0, '["hospitality", "facility_management", "accommodation_coordination"]', 'available'),
(68, 'masters', '["linguistics", "translation", "interpreting", "multilingual communication"]', 'Linguist with expertise in translation and multilingual communication. Can provide translation services and support multilingual communication during emergency response.', '24h', 80.0, '["linguistics", "translation", "multilingual_communication"]', 'available'),
(69, 'bachelors', '["art", "creative therapy", "community healing", "visual communication"]', 'Artist with expertise in creative therapy and visual communication. Can provide creative therapy services and support community healing through art programs.', '24h', 70.0, '["art", "creative_therapy", "community_healing"]', 'available'),
(70, 'vocational', '["tailoring", "clothing repair", "textile work", "emergency clothing"]', 'Tailor with expertise in clothing repair and textile work. Can provide clothing repair services and emergency clothing production during crisis situations.', 'immediate', 67.0, '["tailoring", "clothing_repair", "textile_work"]', 'available'),
(71, 'bachelors', '["photography", "documentation", "visual records", "media support"]', 'Photographer with expertise in documentation and visual records. Can provide visual documentation and media support during emergency operations.', '24h', 74.0, '["photography", "documentation", "visual_records"]', 'available'),
(72, 'masters', '["literature", "writing", "communication", "content creation"]', 'Writer with expertise in communication and content creation. Can support communication efforts and content creation during emergency response operations.', '24h', 76.0, '["literature", "writing", "content_creation"]', 'available'),
(73, 'bachelors', '["drama", "performance", "entertainment", "stress relief"]', 'Actor with expertise in performance and entertainment. Can provide entertainment and stress relief programs during emergency shelter operations.', '24h', 68.0, '["drama", "performance", "entertainment"]', 'available'),
(74, 'associate', '["cooking", "food preparation", "kitchen management", "emergency feeding"]', 'Chef with expertise in food preparation and kitchen management. Can coordinate emergency feeding operations and kitchen management in emergency shelters.', 'immediate', 73.0, '["cooking", "food_preparation", "kitchen_management"]', 'available'),
(75, 'bachelors', '["gardening", "horticulture", "food production", "landscape maintenance"]', 'Horticulturist with expertise in food production and landscape maintenance. Can support emergency food production and maintain green spaces during crisis situations.', '24h', 71.0, '["gardening", "horticulture", "food_production"]', 'available'),
(76, 'masters', '["mathematics", "statistics", "data analysis", "modeling"]', 'Mathematician with expertise in statistics and data analysis. Can support data analysis and modeling efforts during emergency response operations.', '24h', 82.0, '["mathematics", "statistics", "data_analysis"]', 'available'),
(77, 'bachelors', '["physics", "technical analysis", "measurement", "equipment calibration"]', 'Physicist with expertise in technical analysis and equipment calibration. Can provide technical support and equipment calibration during emergency operations.', '24h', 80.0, '["physics", "technical_analysis", "equipment_calibration"]', 'available'),
(78, 'vocational', '["cleaning", "sanitization", "disinfection", "facility maintenance"]', 'Sanitation specialist with expertise in disinfection and facility maintenance. Can coordinate sanitization efforts and maintain clean facilities during emergency response.', 'immediate', 70.0, '["cleaning", "sanitization", "disinfection"]', 'available'),
(79, 'bachelors', '["biology", "environmental monitoring", "health assessment", "research"]', 'Biologist with expertise in environmental monitoring and health assessment. Can support environmental monitoring and health assessment during emergency situations.', '24h', 77.0, '["biology", "environmental_monitoring", "health_assessment"]', 'available'),
(80, 'masters', '["chemistry", "laboratory analysis", "quality control", "testing"]', 'Chemist with expertise in laboratory analysis and quality control. Can provide laboratory support and quality control during emergency response operations.', '24h', 83.0, '["chemistry", "laboratory_analysis", "quality_control"]', 'available'),
(81, 'bachelors', '["geography", "mapping", "spatial analysis", "location services"]', 'Geographer with expertise in mapping and spatial analysis. Can provide mapping support and spatial analysis during emergency response operations.', '24h', 78.0, '["geography", "mapping", "spatial_analysis"]', 'available'),
(82, 'associate', '["office work", "administrative support", "record keeping", "data entry"]', 'Administrative specialist with expertise in record keeping and data entry. Can provide administrative support and data management during emergency operations.', '24h', 72.0, '["office_work", "administrative_support", "record_keeping"]', 'available'),
(83, 'bachelors', '["sociology", "community analysis", "social research", "population studies"]', 'Sociologist with expertise in community analysis and social research. Can support community analysis and social research during emergency response operations.', '24h', 76.0, '["sociology", "community_analysis", "social_research"]', 'available'),
(84, 'masters', '["political science", "policy analysis", "government relations", "coordination"]', 'Political scientist with expertise in policy analysis and government relations. Can support policy coordination and government relations during emergency response.', '24h', 81.0, '["political_science", "policy_analysis", "government_relations"]', 'available'),
(85, 'bachelors', '["psychology", "behavioral analysis", "mental health", "crisis intervention"]', 'Psychologist with expertise in behavioral analysis and crisis intervention. Can provide psychological support and crisis intervention during emergency situations.', '24h', 84.0, '["psychology", "behavioral_analysis", "crisis_intervention"]', 'available'),
(86, 'vocational', '["security", "access control", "surveillance", "emergency security"]', 'Security officer with expertise in access control and surveillance. Can provide security services and surveillance support during emergency operations.', 'immediate', 79.0, '["security", "access_control", "surveillance"]', 'available'),
(87, 'bachelors', '["criminal justice", "law enforcement", "investigation", "evidence handling"]', 'Criminal justice specialist with law enforcement and investigation experience. Can support law enforcement operations and evidence handling during emergency response.', '24h', 85.0, '["criminal_justice", "law_enforcement", "investigation"]', 'available'),
(88, 'masters', '["international law", "humanitarian law", "legal coordination", "rights protection"]', 'International lawyer with expertise in humanitarian law and legal coordination. Can provide legal support and rights protection during emergency situations.', '24h', 87.0, '["international_law", "humanitarian_law", "legal_coordination"]', 'available'),
(89, 'bachelors', '["business", "project management", "resource coordination", "operations management"]', 'Business specialist with expertise in project management and resource coordination. Can support project management and resource coordination during emergency response.', '24h', 80.0, '["business", "project_management", "resource_coordination"]', 'available'),
(90, 'associate', '["customer service", "communication", "support coordination", "information management"]', 'Customer service specialist with expertise in communication and support coordination. Can provide communication support and information management during emergency operations.', '24h', 73.0, '["customer_service", "communication", "support_coordination"]', 'available'),
(91, 'bachelors', '["marketing", "public relations", "communication", "awareness campaigns"]', 'Marketing specialist with expertise in public relations and awareness campaigns. Can support communication efforts and awareness campaigns during emergency response.', '24h', 75.0, '["marketing", "public_relations", "awareness_campaigns"]', 'available'),
(92, 'masters', '["finance", "budget management", "resource allocation", "financial planning"]', 'Financial analyst with expertise in budget management and resource allocation. Can support financial planning and resource allocation during emergency response operations.', '24h', 83.0, '["finance", "budget_management", "resource_allocation"]', 'available'),
(93, 'bachelors', '["accounting", "financial records", "audit", "compliance"]', 'Accountant with expertise in financial records and compliance. Can support financial record keeping and compliance during emergency response operations.', '24h', 77.0, '["accounting", "financial_records", "compliance"]', 'available'),
(94, 'vocational', '["bookkeeping", "data entry", "record keeping", "financial administration"]', 'Bookkeeper with expertise in data entry and record keeping. Can provide administrative support and financial record keeping during emergency operations.', '24h', 71.0, '["bookkeeping", "data_entry", "record_keeping"]', 'available'),
(95, 'bachelors', '["insurance", "risk assessment", "claims processing", "coverage analysis"]', 'Insurance specialist with expertise in risk assessment and claims processing. Can support risk assessment and insurance coordination during emergency response.', '24h', 78.0, '["insurance", "risk_assessment", "claims_processing"]', 'available'),
(96, 'masters', '["real estate", "property management", "facility coordination", "space planning"]', 'Real estate specialist with expertise in property management and facility coordination. Can support facility coordination and space planning during emergency response.', '24h', 79.0, '["real_estate", "property_management", "facility_coordination"]', 'available'),
(97, 'bachelors', '["sales", "relationship management", "coordination", "communication"]', 'Sales specialist with expertise in relationship management and coordination. Can support relationship management and coordination during emergency response operations.', '24h', 74.0, '["sales", "relationship_management", "coordination"]', 'available'),
(98, 'associate', '["retail management", "inventory", "supply coordination", "distribution"]', 'Retail manager with expertise in inventory and supply coordination. Can support supply coordination and distribution during emergency response operations.', '24h', 76.0, '["retail_management", "inventory", "supply_coordination"]', 'available'),
(99, 'bachelors', '["tourism", "hospitality", "visitor services", "coordination"]', 'Tourism specialist with expertise in hospitality and visitor services. Can support hospitality services and visitor coordination during emergency situations.', '24h', 72.0, '["tourism", "hospitality", "visitor_services"]', 'available'),
(100, 'masters', '["management", "leadership", "organizational development", "strategic planning"]', 'Management consultant with expertise in leadership and organizational development. Can support leadership development and strategic planning during emergency response.', '24h', 88.0, '["management", "leadership", "strategic_planning"]', 'allocated');

-- Insert diverse resources with realistic specs
INSERT INTO resources (user_id, category, subtype, quantity, specs_json, available) VALUES
(1, 'comms', 'vhf_uhf', 2, '{"range": "50km", "channels": 25, "encryption": "yes"}', 1),
(1, 'power', 'generator', 1, '{"power_kw": 15, "fuel_type": "diesel", "runtime_hours": 24}', 1),
(3, 'heavy', 'forklift', 1, '{"capacity_kg": 5000, "fuel_type": "diesel", "lift_height_m": 6}', 1),
(3, 'transport', 'van_truck', 2, '{"capacity": "medium", "fuel_type": "diesel", "cargo_m3": 12}', 1),
(5, 'comms', 'ham_license', 1, '{"license_class": "Advanced", "frequency_range": "HF/VHF/UHF", "power_watts": 100}', 1),
(6, 'power', 'battery_bank', 3, '{"capacity_ah": 200, "voltage": "12V", "type": "lithium"}', 1),
(7, 'transport', 'van_truck', 1, '{"capacity": "large", "fuel_type": "diesel", "cargo_m3": 20}', 1),
(9, 'drone', 'fpv', 2, '{"flight_time_min": 25, "range_km": 8, "camera": "thermal"}', 1),
(9, 'drone', 'longrange', 1, '{"flight_time_min": 45, "range_km": 15, "payload_kg": 2}', 1),
(10, 'power', 'generator', 2, '{"power_kw": 25, "fuel_type": "diesel", "runtime_hours": 36}', 1),
(10, 'power', 'solar', 1, '{"capacity_kw": 5, "battery_storage": "yes", "grid_tie": "yes"}', 1),
(11, 'fabrication', '3d_printer', 2, '{"build_volume": "300x300x400mm", "material": "PLA/ABS/PETG", "precision": "0.1mm"}', 1),
(11, 'fabrication', 'cnc', 1, '{"work_area": "1000x600mm", "spindle_power": "3kW", "precision": "0.01mm"}', 1),
(12, 'heavy', 'welder', 1, '{"type": "MIG/TIG", "power_input": "380V", "duty_cycle": "60%"}', 1),
(13, 'heavy', 'welder', 2, '{"type": "ARC/MIG", "power_input": "220V", "duty_cycle": "40%"}', 1),
(14, 'transport', 'van_truck', 1, '{"capacity": "small", "fuel_type": "gasoline", "cargo_m3": 6}', 1),
(16, 'comms', 'vhf_uhf', 1, '{"range": "30km", "channels": 16, "encryption": "no"}', 1),
(17, 'workshop', 'garage', 1, '{"area_m2": 80, "equipment": "full", "heating": "yes"}', 1),
(18, 'power', 'generator', 1, '{"power_kw": 10, "fuel_type": "gasoline", "runtime_hours": 12}', 1),
(20, 'heavy', 'tools', 1, '{"tool_set": "comprehensive", "specialty": "firefighting", "portable": "yes"}', 1),
(22, 'transport', 'offroad', 1, '{"type": "ATV", "capacity": "2 persons", "terrain": "all"}', 1),
(23, 'heavy', 'forklift', 1, '{"capacity_kg": 3500, "fuel_type": "gasoline", "lift_height_m": 4}', 1),
(24, 'comms', 'satellite', 1, '{"type": "portable", "data_rate": "2Mbps", "coverage": "global"}', 1),
(25, 'transport', 'aircraft', 1, '{"type": "helicopter", "capacity": "4 persons", "range_km": 400}', 1),
(26, 'power', 'battery_bank', 2, '{"capacity_ah": 100, "voltage": "24V", "type": "lead_acid"}', 1),
(28, 'workshop', 'garage', 1, '{"area_m2": 60, "equipment": "plumbing", "water": "yes"}', 1),
(30, 'transport', 'van_truck', 1, '{"capacity": "medium", "fuel_type": "diesel", "cargo_m3": 15}', 1),
(32, 'power', 'generator', 1, '{"power_kw": 8, "fuel_type": "gasoline", "runtime_hours": 8}', 1),
(35, 'heavy', 'tools', 1, '{"tool_set": "refrigeration", "specialty": "HVAC", "portable": "yes"}', 1),
(37, 'power', 'solar', 1, '{"capacity_kw": 2, "battery_storage": "yes", "portable": "yes"}', 1),
(40, 'comms', 'weather_station', 1, '{"type": "portable", "sensors": "full", "data_link": "satellite"}', 1),
(42, 'transport', 'van_truck', 1, '{"capacity": "large", "fuel_type": "diesel", "cargo_m3": 25}', 1),
(44, 'comms', 'network_equipment', 1, '{"type": "mobile", "bandwidth": "100Mbps", "encryption": "military"}', 1),
(46, 'transport', 'van_truck', 1, '{"capacity": "medium", "fuel_type": "diesel", "cargo_m3": 18}', 1),
(48, 'power', 'generator', 1, '{"power_kw": 20, "fuel_type": "diesel", "runtime_hours": 30}', 1),
(50, 'transport', 'tractor', 1, '{"type": "agricultural", "power_hp": 80, "implements": "multiple"}', 1),
(52, 'workshop', 'warehouse', 1, '{"area_m2": 200, "equipment": "storage", "access": "truck"}', 1),
(54, 'power', 'battery_bank', 1, '{"capacity_ah": 150, "voltage": "12V", "type": "lithium"}', 1),
(56, 'transport', 'van_truck', 1, '{"capacity": "small", "fuel_type": "gasoline", "cargo_m3": 8}', 1),
(58, 'workshop', 'garage', 1, '{"area_m2": 40, "equipment": "beauty", "utilities": "full"}', 1),
(60, 'comms', 'vhf_uhf', 1, '{"range": "40km", "channels": 20, "encryption": "basic"}', 1),
(62, 'heavy', 'tools', 1, '{"tool_set": "cleaning", "specialty": "sanitation", "portable": "yes"}', 1),
(64, 'transport', 'van_truck', 1, '{"capacity": "medium", "fuel_type": "diesel", "cargo_m3": 14}', 1),
(66, 'power', 'generator', 1, '{"power_kw": 12, "fuel_type": "gasoline", "runtime_hours": 16}', 1),
(68, 'comms', 'translation_equipment', 1, '{"type": "portable", "languages": "50+", "real_time": "yes"}', 1),
(70, 'workshop', 'garage', 1, '{"area_m2": 30, "equipment": "sewing", "utilities": "basic"}', 1),
(72, 'transport', 'van_truck', 1, '{"capacity": "small", "fuel_type": "gasoline", "cargo_m3": 5}', 1),
(74, 'power', 'generator', 1, '{"power_kw": 6, "fuel_type": "gasoline", "runtime_hours": 10}', 1),
(76, 'heavy', 'tools', 1, '{"tool_set": "mathematical", "specialty": "calculation", "portable": "yes"}', 1),
(78, 'workshop', 'garage', 1, '{"area_m2": 50, "equipment": "cleaning", "utilities": "full"}', 1),
(80, 'power', 'battery_bank', 1, '{"capacity_ah": 80, "voltage": "12V", "type": "lead_acid"}', 1),
(82, 'transport', 'van_truck', 1, '{"capacity": "medium", "fuel_type": "diesel", "cargo_m3": 16}', 1),
(84, 'comms', 'vhf_uhf', 1, '{"range": "35km", "channels": 18, "encryption": "no"}', 1),
(86, 'heavy', 'tools', 1, '{"tool_set": "security", "specialty": "surveillance", "portable": "yes"}', 1),
(88, 'transport', 'van_truck', 1, '{"capacity": "large", "fuel_type": "diesel", "cargo_m3": 22}', 1),
(90, 'power', 'generator', 1, '{"power_kw": 4, "fuel_type": "gasoline", "runtime_hours": 6}', 1),
(92, 'workshop', 'warehouse', 1, '{"area_m2": 150, "equipment": "storage", "access": "truck"}', 1),
(94, 'heavy', 'tools', 1, '{"tool_set": "office", "specialty": "administration", "portable": "yes"}', 1),
(96, 'transport', 'van_truck', 1, '{"capacity": "small", "fuel_type": "gasoline", "cargo_m3": 7}', 1),
(98, 'power', 'solar', 1, '{"capacity_kw": 1, "battery_storage": "no", "portable": "yes"}', 1),
(100, 'comms', 'vhf_uhf', 1, '{"range": "45km", "channels": 22, "encryption": "yes"}', 1);

-- Insert sample requests
INSERT INTO requests (authority_id, type, user_id, message, status) VALUES
('hash_authority1', 'info', 1, 'Need additional information about cybersecurity certifications and medical training', 'pending'),
('hash_authority1', 'allocate', 3, 'Emergency construction work needed for infrastructure repair', 'pending'),
('hash_authority1', 'info', 5, 'Requesting details about communication system capabilities', 'pending'),
('hash_authority1', 'allocate', 9, 'Drone surveillance support needed for search operations', 'pending'),
('hash_authority1', 'info', 15, 'Medical team coordination for emergency response', 'pending'),
('hash_authority1', 'allocate', 20, 'Firefighting support for emergency response', 'pending'),
('hash_authority1', 'info', 25, 'Aviation support for emergency transport', 'pending'),
('hash_authority1', 'allocate', 44, 'Cybersecurity support for critical infrastructure protection', 'pending'),
('hash_authority1', 'info', 48, 'Law enforcement coordination for security operations', 'pending'),
('hash_authority1', 'allocate', 88, 'Legal support for emergency operations coordination', 'pending');

-- Insert sample allocations
INSERT INTO allocations (user_id, resource_id, mission_code, status) VALUES
(1, 1, 'MED-CYBER-2024-001', 'active'),
(5, 5, 'COMM-2024-001', 'active'),
(15, NULL, 'MED-EMERGENCY-2024-001', 'active'),
(20, 20, 'FIRE-2024-001', 'active'),
(44, 44, 'CYBER-DEFENSE-2024-001', 'active'),
(88, NULL, 'LEGAL-2024-001', 'active'),
(100, 100, 'MANAGEMENT-2024-001', 'active');
